### ISSUE TITLE
Windows版本报毒

### ISSUE THREAD

**Issue by azgh** [cuiocean/ZY-Player#316]
![image](https://user-images.githubusercontent.com/11712776/97107387-39add880-1702-11eb-8919-44dc2317a053.png)
Windows10系统chrome现在安装文件报毒。

**Comment by azgh** [comment]
@cuiocean 这个问题没人关注吗？

**Comment by Hunlongyu** [comment]
现在最新版时 2.5.4 , 还报错么?

**Comment by warden22** [comment]
没遇到啊，你的报错就报错，把杀毒关闭就行了

**Comment by azgh** [comment]
> 现在最新版时 2.5.4 , 还报错么?

明天用windows试一下

**Comment by azgh** [comment]
> 没遇到啊，你的报错就报错，把杀毒关闭就行了

杀毒软件报毒，就把杀毒关了，那去体检发现异常，是不是要把医生灭口？开个玩笑：）
还是Owner负责任啊，给 @Hunlongyu 点赞

**Comment by azgh** [comment]
@Hunlongyu 最新版2.5.7还是报毒。
![image](https://user-images.githubusercontent.com/11712776/97646377-6c512b80-1a8a-11eb-8bb8-27a6ac913e54.png)

**Comment by gitfortune** [comment]
最新版 2.6.1 报毒

**Comment by gitfortune** [comment]
windows拦截  特洛伊病毒

**Comment by qianxinxin0525** [comment]
这个不是很简单吗，你相信就用，怕中毒就不用，我是没有这个提示的。

![image](https://cdn.jsdelivr.net/gh/qianxinxin0525/test123@main/QQ%E5%9B%BE%E7%89%8720201105215556.png)

**Comment by buvta** [comment]
因为很多源站加载图片https时存在错误，需要开启“忽略证书错误”，而这可能导致windows报毒

v2.7.0rc及上述提到的版本全部用[在线杀毒virustotal](https://www.virustotal.com/)查杀过报告正常
