### ISSUE TITLE
Mac版本,不知道该怎么制定第三方播放软件

### ISSUE THREAD

**Issue by sj13824803000** [cuiocean/ZY-Player#335]
如题
发现点击使用第三方播放软件时,选中其他的播放软件都是灰色的. 不能点确定
![image](https://user-images.githubusercontent.com/24707427/97843182-d1737e00-1d23-11eb-854e-be9e63b7b09a.png)

**Comment by Darling-Lee** [comment]
先finder（访达）手动打开你的application（应用程序），选中你要用的播放器（需要支持网络播放的播放器，例如IINA），然后右击显示包内容，再进到Contents->MacOS,这里面就有程序的可执行文件（一般跟软件同名，比如IINA播放器，这里面就有个IINA的文件，然后复制这个文件的路径下来（怎么复制路径具体方法请自行百度，或者不怕麻烦就稍后手动输入）这个步骤就是找到你要定义的播放器的可执行文件的绝对路径。然后再去ZY-PLAYER的第三方播放器设定处有个编辑的按钮，把可执行文件的绝对路径粘贴进去。例如我的IINA路径就是/Applications/IINA.app/Contents/MacOS/IINA（注意不是可执行文件所在路径，必须定义到文件，即最后的IINA是指定到了IINA这个可执行文件。

不过我还是建议开发大大，能够支持直接选择应用程序（后缀名为.app的文件夹里面的结构是/Contents/MacOS/$程序名），不至于这么麻烦。

**Comment by 87926042** [comment]
第三方播放直接设置选择第三方播放器，灰色的话选择左下角的选项，然后将类型改成全部就能够选择了
