### ISSUE TITLE
请问是有tv版了吗？

### ISSUE THREAD

**Issue by hualuoshuijia** [cuiocean/ZY-Player#357]
https://www.right.com.cn/forum/thread-4058318-1-1.html

![image](https://user-images.githubusercontent.com/49584289/99900552-ffc4f780-2cea-11eb-86c3-5f772b0ca366.png)

**Comment by myjlpt** [comment]
目测应该是用了神马的壳子，加上全网资源的作品。应该和本软体没半毛钱关系。

**Comment by Hunlongyu** [comment]
嗯~ 并不是我们开发的, 我们的TV版项目: https://github.com/cuiocean/ZY-Player-TV

**Comment by myjlpt** [comment]
呵呵，其实现在到无所谓有没有TV了。有源链接，自动生成的m3u8，拖到TV版的骆驼壳播放就拉倒了。除了麻烦点

**Comment by cuiocean** [comment]
我个人盒子上用的是FreedTV 它支持自定义源 基本满足我所有的需求了 在它不能用之前不会开发ZY TV版 下载地址 https://wwi.lanzous.com/b025mpw7e
