### ISSUE TITLE
跪求大佬开发 Android-TV版。。。

### ISSUE THREAD

**Issue by Jamie-LinXJ** [cuiocean/ZY-Player#367]
这个看片神器要是能安装到电视上简直秒杀电视上那些看个老片还动不动就要会员的应用，可现在的Android版安装到电视后得用鼠标操作。。。

**Comment by FanchangWang** [comment]
同求，同求，希望能出个 TV 版

**Comment by FanchangWang** [comment]
找到 TV 版的项目库了，哈哈

https://github.com/cuiocean/ZY-Player-TV

**Comment by SmallWinter** [comment]
> 找到 TV 版的项目库了，哈哈
> 
> https://github.com/cuiocean/ZY-Player-TV

这个TV版还在开发吧，还没开发完

**Comment by FanchangWang** [comment]
> > 找到 TV 版的项目库了，哈哈
> > https://github.com/cuiocean/ZY-Player-TV
> 
> 这个TV版还在开发吧，还没开发完

已经快 20 天没提交过代码了。。。

**Comment by lshilshi** [comment]
同求，之前网上找了几个，全是第三方打包的，加了一对广告和自家网站的推广，恶心死了

**Comment by qwerttvv** [comment]
一起蹲一波儿，不知道进度条儿走到哪儿了

**Comment by drw2005** [comment]
能有TV那真是太好了。

**Comment by Aurora-LiZhi** [comment]
要是加入TV版  那不是美滋滋

**Comment by cuiocean** [comment]
我个人盒子上用的是FreedTV 它支持自定义源 基本满足我所有的需求了 在它能用之前不会开发ZY TV版 下载地址 https://wwi.lanzous.com/b025mpw7e
