### ISSUE TITLE
 添加支持外挂字幕的功能？

### ISSUE THREAD

**Issue by crazypeace** [cuiocean/ZY-Player#607]
**描述您想要的解决方案**
支持外挂字幕

**描述您考虑过的替代方案**
导出播放链接，用potplayer播放再挂字幕。但是potplayer播放不出来。

**Comment by cuiocean** [comment]
大部分片源不都是有字幕的吗? 请给个例子,和你要加载的字幕文件.

**Comment by crazypeace** [comment]
前天看《心灵奇旅》，就是没字幕的。我今天去看原链接，已经加上字幕了。
我要加载的字幕就是网上下载的，不是什么特殊的版本。比如：http://www.rikua.com/zimu/srt.aspx?zd=2&id=8671

**Comment by cuiocean** [comment]
这个需求的覆盖面太小 不值得做 所以先关闭这个issue了
