### ISSUE TITLE
在精简模式下  打开电脑的  开始菜单  会出现黑屏情况

### ISSUE THREAD

**Issue by hualuoshuijia** [cuiocean/ZY-Player#611]
在精简模式下  打开电脑的  开始菜单  会出现黑屏情况
![image](https://user-images.githubusercontent.com/49584289/103404886-30246f00-4b90-11eb-902b-99bea415c14d.png)

**Comment by hualuoshuijia** [comment]
![image](https://user-images.githubusercontent.com/49584289/103404917-4fbb9780-4b90-11eb-96ab-b6f3236cdaa3.png)

**Comment by buvta** [comment]
该bug依赖上游解决
