### ISSUE TITLE
手机版被检查为威胁病毒软件是怎么回事

### ISSUE THREAD

**Issue by Lucky-CYZ** [cuiocean/ZY-Player#613]

**Comment by chai233202** [comment]
对的，手机版本下载后，一直显示是危险软件，一不小心就会点删除！

**Comment by Hunlongyu** [comment]
目前叫 zy 的手机版有很多呢，我只能保证从我官网下载的没有任何问题。 其他渠道下载的很有可能被人篡改过。
如果从我官网下载的有问题。可能是因为视频里包含了 一些 成人视频。 虽然做了过滤处理， 依旧会有一些没有过滤掉。

chai233202 <notifications@github.com> 于2021年1月7日周四 下午6:43写道：
