### ISSUE TITLE
win版,全屏有大概率会漏边

### ISSUE THREAD

**Issue by joshatt** [cuiocean/ZY-Player#623]
**描述错误**
清楚简洁地说明错误是什么。
播放的时候, 全屏, 有90%概率会漏边, 左和上漏2毫米, 下露出整个程序栏

**重现**
重现行为的步骤
win7笔记本, 分辨率1366x768.  无论是正常模式还是精简模式, 都如此

**预期行为**
对您期望发生的事情的简洁明了的描述。

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题（直接把图片拖到编辑框即可添加图片）。

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 18362.156]   
win7 x64
  -软件安装包及版本：[例如：Windows 64位绿色版 1.0.0]    
win 2.7.1

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by cuiocean** [comment]
无法重现
