### ISSUE TITLE
添加电视剧下载功能

### ISSUE THREAD

**Issue by zero-hugo** [cuiocean/ZY-Player#636]
我现在基本上都在软件里追剧，但因为工作原因，经常会不能连WIFI，于是就将电视剧下载在电脑里带着看。但软件里的电视剧无法下载，只能去网上找，找老半天，然后一集一集的复制下载链接到迅雷里，费时费力。要是软件能直接将全集的电视剧缓存到本地来，就方便很多了。

**Comment by buvta** [comment]
github搜索m3u8 download
