### ISSUE TITLE
希望可以支持自定义主题（前景色、后景色、强调色）

### ISSUE THREAD

**Issue by XIU2** [cuiocean/ZY-Player#639]
软件很棒，但是感觉软件主题配色有点。。。

****

- **白色主题**  
_还不错，除了和播放界面的**黑色对比太大**有点别扭，考虑到很多视频播放器都喜欢深色、黑色，于是我试了下黑色主题..._
- **黑色主题**  
_有点无法接受这个**绿色阴影**。。。感觉这个配色比较奇怪（仅代表个人）！_

![1](https://user-images.githubusercontent.com/54703944/106979435-429a5580-6799-11eb-8814-ec34533fa299.png)

****

不过考虑到审美差异，希望支持**自定义主题（即前景色、后景色、强调色）**。

> 可以是对现有的主题自定义，也可以是专门整个自定义用的主题。

如果比较麻烦的话，就算了，反正只是一些细节。。。

**Comment by buvta** [comment]
可以自行调整配色方案src/assets/scss/theme.scss后打包

**Comment by XIU2** [comment]
不太懂具体该如何打包。。。

**Comment by buvta** [comment]
可以参考#617，yarn最好配置下国内源以加速

**Comment by XIU2** [comment]
OK
