### ISSUE TITLE
弄了一套视频源，但是出现了导入不了的问题 不知道是哪出了错

### ISSUE THREAD

**Issue by Louis209** [cuiocean/ZY-Player#642]
版本
2.7.3
操作系统
windows10 20H2

### 描述问题：
弄了一套视频源，但是出现了导入不了的问题 不知道是哪出了错
求大佬帮助

### json下载地址
https://77y-my.sharepoint.com/:u:/g/personal/wangpan_77y_org/EVMi185qvN9Eqf9Hqa74VZwBvF5I45hlqpilc2P5maLa5w?e=vITNEp

**Comment by Louis209** [comment]
已解决

**Comment by 2528177712** [comment]
怎么解决的  大哥

**Comment by Portan** [comment]
兄弟，视频源从哪里获取的？

**Comment by Louis209** [comment]
> 兄弟，视频源从哪里获取的？

邮箱留下，我发你

**Comment by 2528177712** [comment]
2528177712@qq.com   谢谢了

**Comment by Louis209** [comment]
> [2528177712@qq.com](mailto:2528177712@qq.com) 谢谢了

已发
