### ISSUE TITLE
视频源消失了。 

### ISSUE THREAD

**Issue by itnewgay** [cuiocean/ZY-Player#647]
### 版本、安装方式、系统

1. 你在使用什么版本的
2.73

2. 你通过什么方式安装
本站下载
3. 你所使用的操作系统
WIN1O

### 描述问题： 所有的视频源消失了。如何找回呢？ 重新安装也没有用。
![image](https://user-images.githubusercontent.com/43598975/107875852-287d1780-6efd-11eb-9c5f-e62aae137fcf.png)

**Comment by YangtseSu** [comment]
Linux ，同样的问题。
解决方案： $ rm -rf ~/.config/zy

**Comment by lovexiaov** [comment]
Win10 同样的问题，求高手解答

**Comment by Lynn-7** [comment]
Mac也是，根本上不了网

**Comment by jiehua1995** [comment]
可以先在2.7.2保存Json，然后更新完再导入进去。

**Comment by cuiocean** [comment]
下一版本会支持从github网站读取源站文件,而且可以自行设置在线的json文件.

**Comment by mumuyiren** [comment]
搜索框无效，搜什么剧，怎么搜，什么都搜不出来
