### ISSUE TITLE
（未回答的问题请删除，减少多余信息干扰）

### ISSUE THREAD

**Issue by lw1223** [cuiocean/ZY-Player#653]
**描述错误**
鼠标移动到片库底部，片库会“晃动”

**重现**
鼠标移动到截图位置

**预期行为**

**截图**
![image](https://user-images.githubusercontent.com/59414429/109266727-61918200-7843-11eb-8f25-9f92755d4bd1.png)

**环境：**
  -操作系统及版本：Windows 10 64位 19042.804
  -软件安装包及版本：v2.7.5 64位

**Comment by cuiocean** [comment]
已解决.在下一版本中放出.
