### ISSUE TITLE
看视频卡

### ISSUE THREAD

**Issue by itnewgay** [cuiocean/ZY-Player#656]
### 版本、安装方式、系统

1. 你在使用什么版本的 2.75

2. 你通过什么方式安装 github

3. 你所使用的操作系统 win10

### 描述问题：

看视频总是一卡一卡的，怎么回事啊。。几乎没有流畅过。。。

**Comment by cuiocean** [comment]
一般视频卡顿都是片源问题,建议更换视频源试试看.

**Comment by itnewgay** [comment]
各种换也没用. 我是100M宽带。自己一个人用的。。

**Comment by phicommvip** [comment]
我感觉除了和片源有关系外也和运营商有一定关系，比如某片源用的联通的服务器而你用的电信或移动的宽带速度就会慢一些

**Comment by cuiocean** [comment]
如果视频卡 可以在第三方播放器或在线播放器里打开该视频m3u8链接 确认同一视频是否只在zy里卡 我很怀疑这一点
