### ISSUE TITLE
希望收藏列表增加批量换源功能

### ISSUE THREAD

**Issue by lizhi123le** [cuiocean/ZY-Player#657]
希望收藏列表增加批量换源功能

**Comment by buvta** [comment]
有必要吗？看的时候一次只能播放一个啊
如果认为必要，请说明下目的和使用场景

**Comment by lizhi123le** [comment]
有的源失效了，收藏的视频无法播放，不能批量换源也要支持单个换源，不然收藏的视频又要重新搜索。这次永久资源失效了，之前收藏的十几个视频全部无法播放，收藏又不能换源只能重新一个一个搜索。所以希望PC版收藏列表在源站那一列增加按钮功能来支持换源，就像播放界面的换源按钮一样，挺方便的。

**Comment by lizhi123le** [comment]
> 有必要吗？看的时候一次只能播放一个啊
> 如果认为必要，请说明下目的和使用场景

有的源失效了，收藏的视频无法播放，不能批量换源也要支持单个换源，不然收藏的视频又要重新搜索。这次永久资源失效了，之前收藏的十几个视频全部无法播放，收藏又不能换源只能重新一个一个搜索。所以希望PC版收藏列表在源站那一列增加按钮功能来支持换源，就像播放界面的换源按钮一样，挺方便的。

**Comment by buvta** [comment]
已修复，请等待新版发布
利用播放页面原有的换源及收藏功能，请在换源前点击播放器下方的收藏按钮取消收藏(若已收藏)，换源后重新收藏
