### ISSUE TITLE
替zy鸣不平，强烈反对仰仗zy开源去谋财。希望大家在此举报

### ISSUE THREAD

**Issue by xiangfeigao** [cuiocean/ZY-Player#659]
首先感谢cuiocean给大家带来的zy-player，用起来很干净。但是有人利用zy资源去发财，我很生气，强烈建议cuiocean管管他们吧，我们支持你，也感谢你，不让那些利欲熏心的人，把咱们的初衷和净土污染。
这些广告制作垃圾，妨碍观看，对zy产生了负面影响。

举报内容：
插入大量广告：
https://github.com/vicedev/ZY-Player-Android

**Comment by buvta** [comment]
开源项目不作恶就好，不能要求人人都用爱发电

**Comment by cuiocean** [comment]
@xiangfeigao 多谢提醒. 我看它的项目也是开源的.即使不是,我们也做不了什么. 我们的项目是MIT协议的,你可以随意更改,发布,商用都行. 另外,你说的广告,是视频内广告还是app内自加的广告? 我们也有自己的安卓app, https://github.com/cuiocean/ZY-Player-APP

**Comment by luckyfatpig** [comment]
这个版本我也在用，官方版的之前也安装了，无奈官方版的没有全局搜索和投屏功能，于是就卸载了官方版的

**Comment by xihaceo** [comment]
屏蔽汇量科技广告即可  域名为  rayjump.com
