### ISSUE TITLE
无法导入解析源，手动和文件都无法

### ISSUE THREAD

**Issue by ioslide** [cuiocean/ZY-Player#662]
### 版本、安装方式、系统

1. 你在使用什么版本的 2.7.6

2. 你通过什么方式安装 msi

3. 你所使用的操作系统 win10 20H2

### 描述问题：
无法导入解析源，手动和文件都无法

**Comment by Sun2yu** [comment]
你可以按照官方常见问题页面的方法情理文件解决：

9. 安装新版本后不工作/部分功能不正常

数据文件夹位置可参考相应系统下chrome的配置文件夹路径
Windows下,请清理 AppData\Roaming\zy文件夹
linux下，请清理~/.config/zy
MacOS下，请清理Users/用户名/Library/Application Support/zy
MacOS更新报错，重新安装打不开A JavaScript error occurred in the main process请参考 #593
清理后重置软件，再重试.
安装新版后部分功能不正常也可以按上述操作，如果还是不行请报bug
