### ISSUE TITLE
提升搜索的质量

### ISSUE THREAD

**Issue by qyingkou** [cuiocean/ZY-Player#666]
**描述错误**
搜索结果中总是参杂着很多无用的信息
完全匹配项却在最后一个显示

**重现**
输入框中输入“小小少年”，拉到底部查看

**预期行为**
完全匹配项应该在最前面显示

**截图**
<img width="1080" alt="截屏2021-03-26 上午11 33 33" src="https://user-images.githubusercontent.com/46431594/112748597-4dca6e80-8fef-11eb-9f22-9d5f68c94374.png">
如图所示，完全匹配的却在最下方显示

**环境：**
  -操作系统及版本：macos Big Sur 11.2.3 (20D91)
  -软件安装包及版本：ZY Player 版本2.7.0 (2.7.0)

**其他内容**
请调整搜索项的数量和位置，使得搜索结果变少更精确。

**Comment by cuiocean** [comment]
请升级到最新版本,该问题已经解决了.
![Uploading image.png…]()
