### ISSUE TITLE
历史记录添加更新功能 

### ISSUE THREAD

**Issue by ghaner** [cuiocean/ZY-Player#667]
**历史记录添加更新功能 **

**Comment by cuiocean** [comment]
就是和收藏类似的更新功能呗,点击一下有更新的记录上添加个"有更新"提示?

**Comment by ghaner** [comment]
> 就是和收藏类似的更新功能呗,点击一下有更新的记录上添加个"有更新"提示?

是的.收藏的视频时间长了会很多,而且很多不需要删除的.历史记录里面可以删除一些看过的.那些追剧的更新在历史记录里面比较容易寻找.

**Comment by cuiocean** [comment]
会考虑在下一版本里加入

**Comment by cuiocean** [comment]
@ghaner 已实现, 请期待下一版本. 新的历史页面工具栏
![image](https://user-images.githubusercontent.com/5760235/112845439-26ce7400-90a5-11eb-8df4-330e7c812137.png)

**Comment by cuiocean** [comment]
请升级到2.7.9
