### ISSUE TITLE
一个不重要的问题反馈（关于皮肤）

### ISSUE THREAD

**Issue by phicommvip** [cuiocean/ZY-Player#668]
用的黑色皮肤但是软件启动的时候还是以默认的白色皮肤启动的然后才显示黑色皮肤，这个其实没有任何影响就顺便提一下，另外如果有时间了建议多几个可以选择的皮肤纯色背景太单调了。

最后再说一次皮肤问题不重要没有任何影响，请大佬根据自己的心情酌情添加就好

**Comment by cuiocean** [comment]
确实，皮肤会先加载默认的白色皮肤才能调整为设置里的皮肤。可惜不大好解决
