### ISSUE TITLE
添加演员 导演搜索功能 

### ISSUE THREAD

**Issue by ghaner** [cuiocean/ZY-Player#669]
1.资源采集站一般都支持演员 导演姓名为关键词的搜索。希望zy增加这样的搜索功能.谢谢
![李连杰](https://user-images.githubusercontent.com/51288907/112911999-14285f00-90e6-11eb-9a4b-183c01b02595.png)

2.建议在详情页面增加相似影视剧功能(推荐或猜你喜欢),推荐同题材 演员 导演等有类似属性标签的影视剧.
![推荐](https://user-images.githubusercontent.com/51288907/112912254-a7fa2b00-90e6-11eb-8d63-be329187382b.png)

**Comment by cuiocean** [comment]
@ghaner 多谢建议. 第一个需求比较难实现,那些视频源都没有提过搜索演员等别的信息的接口.第二个功能需求已经实现.

**Comment by ghaner** [comment]
> @ghaner 多谢建议. 第一个需求比较难实现,那些视频源都没有提过搜索演员等别的信息的接口.第二个功能需求已经实现.

大师给力,提过三个功能请求除了这个第一个建议其他两个建议都实现了,谢谢!现在zy是开机自启动程序.越来越喜欢了.

**Comment by cuiocean** [comment]
你可以升级到2.8.0了. 我将关闭这个ticket.
