### ISSUE TITLE
几个小建议

### ISSUE THREAD

**Issue by phicommvip** [cuiocean/ZY-Player#678]
1：解析出来的视频看到一半不看了下次再看就从头开始播了，能不能给加个记忆播放进度的功能啊

  2：遇到卡顿的时候当然是换源了，换源后播放记录就会变成两个有时候多换几次就会变成好几个记录挨个删除有点麻烦，而且有时候都记不清哪一个速度快的了，能不能在换源成功后自动删除上一个源的记录

  3：建议把有更新这个选项放到检查更新的附近，这样就不用每次都点一下工具栏了

最近好多视频源失效找了一些新的源发现很多都需要解析，而解析出来的经常遇到一些小问题希望大佬有时间了可以完善一下

**Comment by cuiocean** [comment]
第三个建议已经完成.

**Comment by cuiocean** [comment]
解析视频本来也不是这个软件关注的重点. 软件内置的源我在用,都还没问题呢. 你可以看看这个文件https://github.com/cuiocean/ZY-Player-Resources/blob/main/Sites/Sites.json

**Comment by Louis209** [comment]
记忆播放可以找那种支持记忆的解析接口

**Comment by cuiocean** [comment]
比如？每个源都可以设置自己的解析接口的

**Comment by buvta** [comment]
保存解析站cookie可实现记忆进度，有点麻烦
如果确实需要请调用浏览器播放，播放页面点击“调试”选取解析播放链接(非m3u8,地址多会包含"share")复制到浏览器打开
