### ISSUE TITLE
能否添加电影名 关键词过滤啊  ok资源网有个电影解说的板块  有些讨厌，

### ISSUE THREAD

**Issue by hualuoshuijia** [cuiocean/ZY-Player#679]
![image](https://user-images.githubusercontent.com/49584289/113507679-99948f00-957e-11eb-847f-07c646dd254f.png)
zh这是手机版的zy播放器 关键词过滤，

**Comment by cuiocean** [comment]
已添加自定义过滤关键词功能,请更新到2.8.1 @hualuoshuijia
