### ISSUE TITLE
大白屏不是个小问题

### ISSUE THREAD

**Issue by qyingkou** [cuiocean/ZY-Player#682]
### 版本、安装方式、系统
1. 你在使用什么版本的：2.7.7
2. 你通过什么方式安装：macos dmg binary
3. 你所使用的操作系统：macos big sur

### 描述问题：
<img width="851" alt="截屏2021-04-05 下午12 50 06" src="https://user-images.githubusercontent.com/46431594/113538615-436f2c80-960e-11eb-93b5-d03f6729460c.png">
如图，搜索中是一个大白屏，等了10分钟还是个大白屏！
虽然只是个体验问题，但这跟可用性扯上关系了。

建议：

- 将搜索过程尽量透明化。比如A网站找到2个结果、B网站找到3个结果，不要同步返回而是流式返回。

- 超时或无内容时候需要告知用户，甚至给出一些相近的关键词。

- 有些资源找不到，我不清楚是我的模糊搜索关键词问题，还是你们数据库中没有。可否支持一些复杂搜索的语法，比如or and not之类的哈？

以上问题都和搜索的体验相关

**Comment by buvta** [comment]
先将源检测一遍再搜索
搜索只是调用源站的搜索api，我们没有服务器不会收集关键词，故而无法提供搜索建议
可以尝试使用工具栏过滤下搜索结果

**Comment by cuiocean** [comment]
改进了一下搜索功能，目前是不会一直保持在搜索中状态了。请更新到2.8.1
