### ISSUE TITLE
现在是不是不能导入源了?

### ISSUE THREAD

**Issue by lyuinc** [cuiocean/ZY-Player#686]
2.8.0版本的 导入源 重置还是干嘛的 点到主要之后，导入的源马上就没了，换了一个主题，换了之后再点击其他的主题就不管用了。这都是什么鬼啊

**Comment by cuiocean** [comment]
请组织一下语言,详细描述一下如何重现你的问题, 一步一步都怎么做. 我看不懂你的描述.
