### ISSUE TITLE
mac版界面报错

### ISSUE THREAD

**Issue by PeiAlan** [cuiocean/ZY-Player#687]
打开软件界面 资源初始化无效
显示：No results :(
![image](https://user-images.githubusercontent.com/33126641/113972350-0b195980-986d-11eb-93b9-506e32038e5f.png)

**Comment by cuiocean** [comment]
你用的哪个版本? 请先升级到最新版本, 如果问题还在, 在设置,编辑源页面,点一下重置试试?

**Comment by HelipengTony** [comment]
遇到同样问题。
系统版本：macOS 11.2.3
软件版本：2.8.0

安装包为 Github Release 下载的 ZY-Player-2.8.0.dmg，已尝试在设置编辑源页面点重置

<img width="1080" alt="1" src="https://user-images.githubusercontent.com/21199796/114264583-532bae00-9a1e-11eb-9b30-8e2e0cd08847.png">
<img width="1080" alt="2" src="https://user-images.githubusercontent.com/21199796/114264586-558e0800-9a1e-11eb-8878-c62da71e92b5.png">
<img width="1080" alt="3" src="https://user-images.githubusercontent.com/21199796/114264590-56bf3500-9a1e-11eb-89de-8fbbc3fdc6df.png">

**Comment by cuiocean** [comment]
奇怪. 你试试导入源呢?

**Comment by PeiAlan** [comment]
我现在打开，没问题了呢，也没有点重置
![image](https://user-images.githubusercontent.com/33126641/114265293-97b94880-9a22-11eb-916f-98cb9e258828.png)

**Comment by PeiAlan** [comment]
有点奇怪

**Comment by HelipengTony** [comment]
点了软件重置，可以正常使用了。
