### ISSUE TITLE
播放控制控件无法操作问题

### ISSUE THREAD

**Issue by dXrayb** [cuiocean/ZY-Player#689]
**描述错误**
全屏时，鼠标移至屏幕底部，播放控件出现，但是如果移动到按钮或者进度条时，播放控制空间消失，只能还原至窗口模式操作。

**重现**
全屏播放时有一定几率出现

**环境：**
  -操作系统及版本：Windows 10 64位 19042.867

**Comment by cuiocean** [comment]
可以重现这个问题，可我现在还不知道为啥会这样。

**Comment by buvta** [comment]
我测试了下linux下全屏似乎没问题，不过精简模式调整窗口大小后鼠标移到左下角附近播放控件不会显示

**Comment by cuiocean** [comment]
已解决， 虽然解决的方法很粗暴，就是把那几个按钮往右移动了一下。😄。请更新到2.8.3
