### ISSUE TITLE
例如：添加在线视频缓存功能

### ISSUE THREAD

**Issue by OneShaozi** [cuiocean/ZY-Player#694]
**描述您想要的解决方案**
软件里面添加视频缓存功能。我现在看到有一个下载按钮，但是只是复制链接，接下来就不知道怎么下载了

**描述您考虑过的替代方案**
对您考虑过的所有替代解决方案或功能的简洁明了的描述。

**其他内容**
在此处添加有关功能请求的任何其他上下文或屏幕截图（直接把图片拖到编辑框即可添加图片）。

**Comment by buvta** [comment]
请在github搜索m3u8 download
