### ISSUE TITLE
无法显示资源，重置无效

### ISSUE THREAD

**Issue by zhaixiuyan** [cuiocean/ZY-Player#696]
**描述错误**
*检测到视频源未能正常加载, 即将重置源.
无法显示资源，重置无效

**重现**
必现

**环境：**
  -操作系统及版本：elelmentary os  linux
  -软件安装包及版本：ZY-Player-2.8.2.AppImage

**Comment by BruceAn1978** [comment]
安装后打开就提示同样的错误信息，新手求指导。
