### ISSUE TITLE
Bug：豆瓣热门推荐无法加载

### ISSUE THREAD

**Issue by zky104** [cuiocean/ZY-Player#701]
## 截图
![360截图20210424155456751.jpg](https://i.loli.net/2021/04/24/LU5xtWrSuoqlpGH.jpg)
## 其他
其他和豆瓣有关的排行榜都无法加载
## 平台
Windows10 x64 1909
客户端：v2.8.4

**Comment by cuiocean** [comment]
你的当前源工作嘛？它是从当前源里搜数据
