### ISSUE TITLE
Mac版本数据源加载不出来

### ISSUE THREAD

**Issue by fumenyaolang** [cuiocean/ZY-Player#702]
**描述错误**
1、数据源无数据
2、设置中数据源也无数据

**截图**
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/12332849/115957014-a0397500-a532-11eb-8808-1e0eb303df7d.png">

**环境：**
  -mac 11.2

**Comment by cuiocean** [comment]
如果重置无效的话 请自行导入源
