### ISSUE TITLE
检查更新信息不准确

### ISSUE THREAD

**Issue by phicommvip** [cuiocean/ZY-Player#703]
版本号：2.8.4

播放记录里点击检查更新信息不够准确，比如有的剧没有更新却显示有更新，还有的明明有更新也提示有更新了但是显示的更新信息不准确、比如这个仙武帝尊更新到34集了备注也显示更新到34但是可能是因为线路的问题所以还是显示共32集，只能换个线路才显示34

**Comment by cuiocean** [comment]
检测更新只检查你使用的那个线路的更新.
