### ISSUE TITLE
win10 64位下载中止

### ISSUE THREAD

**Issue by oreoreoeo** [cuiocean/ZY-Player#705]
之前下载过不小心卸了 现在重新下载完安装包可是app下不了进度条只能在一半那里

**Comment by Hunlongyu** [comment]
https://pd.zwc365.com/seturl/https://github.com/cuiocean/ZY-Player/releases/download/v2.8.4/ZY-Player-Setup-2.8.4.exe

**Comment by oreoreoeo** [comment]
> https://pd.zwc365.com/seturl/https://github.com/cuiocean/ZY-Player/releases/download/v2.8.4/ZY-Player-Setup-2.8.4.exe

还是不可以欸就和我之前试过的一样 这个可以成功下载 但是下载完想打开 安装进度会卡在中间被中止

**Comment by buvta** [comment]
试试先卸载再安装
