### ISSUE TITLE
视频加载不出来

### ISSUE THREAD

**Issue by oreoreoeo** [cuiocean/ZY-Player#708]
### 版本、安装方式、系统

1. 8.2

2. githhub (输入密钥）

3. win 10

### 描述问题：

视频加载半天不出来，一直在转圈圈。但是播另一个历史播过的可以
补充下 这个加载不出来的是 ”爱，死亡和机器人“ 这部剧

**Comment by cuiocean** [comment]
请不要报告类似源站失效了 视频无法播放等类的错误 这不在本软件控制范围之内 你可以换个源站试试
