### ISSUE TITLE
请优化一下界面操作-win版

### ISSUE THREAD

**Issue by jefcn** [cuiocean/ZY-Player#709]
1.推荐页和首页顶部的工具栏能否统一设计？其实功能项基本都一致啊。现在推荐页显示工具栏后会有折行（将窗口缩小一点即可看见）
2.启动软件时恢复窗口大小和位置会有延迟（就是仍然有个缩放的过程），优化一下更好。
3.win版界面如果统一成uwp程序风格更好，比如右上角的4个按钮取win10系统默认的。

另外，是否可内置几个无水印广告的源？现在内置的基本上都是赌博组织推广网站，视频满屏广告，观看体验很糟糕。如果作者的初衷本意如此，当我没说，哈哈

**Comment by cuiocean** [comment]
1, 因为推荐页面的工具多了一列,所有窗口缩小的时候会有折行. 不影响使用,暂时不会处理.
2. 这个之前有人提过,暂时没有好的解决办法.
3. 不同人有不同的风格爱好,别的人可能会喜欢另外一种风格了. 不会处理.
4. 寻找好的视频采集源不在本软件处理范围. 软件支持自行添加源,请自行添加. 另外,最近好多视频站都被关闭了,且用且珍惜吧.
