### ISSUE TITLE
程序界面突然显示比例异常

### ISSUE THREAD

**Issue by sdlp2000** [cuiocean/ZY-Player#710]
### 版本、安装方式、系统

1. 使用PC版的2.8.4

2. 通过安装文件安装

3. 所使用的操作系统 win10

### 描述问题：

界面整体缩小，例如按钮、文字、图片，如截图所示，请给个解决方法
![截图20210513225313](https://user-images.githubusercontent.com/46844430/118143623-2401c580-b43e-11eb-996c-7ebf8816f104.png)

**Comment by cuiocean** [comment]
是你的显示设定问题,你可以把缩放比例调为200%
![image](https://user-images.githubusercontent.com/5760235/118354276-aa1b2a80-b56a-11eb-9f1a-e627f258e23b.png)
