### ISSUE TITLE
建议给不同源定义逆序或者顺序首页，跳转页面功能

### ISSUE THREAD

**Issue by yimiha** [cuiocean/ZY-Player#711]
软件现在更新的第一页是返回查询数据的最后一页，但有好多源更新是逆序，第一页是最新的，最后一页是最老的。是否可以在源管理添加相关设置选项？还有建议在工具栏设置显示总页面数，手动输入跳转页面，方便浏览。

**Comment by cuiocean** [comment]
@yimiha 2.8.5支持每个源站定义是否倒序排列
