### ISSUE TITLE
历史记录 如连续剧还在更新中的 目前无法同步 或者刷新（未回答的问题请删除，减少多余信息干扰）

### ISSUE THREAD

**Issue by ciclaminosr** [cuiocean/ZY-Player#712]
**描述错误**
清楚简洁地说明错误是什么。

**重现**
重现行为的步骤

**预期行为**
对您期望发生的事情的简洁明了的描述。

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题（直接把图片拖到编辑框即可添加图片）。

**环境：**
  -操作系统及版本：[例如：Windows 10 64位 18362.156]
  -软件安装包及版本：[例如：Windows 64位绿色版 1.0.0]

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by ciclaminosr** [comment]
我记得以前有个版本，某连续剧还在更新，我们在追剧。
然后历史记录里面 操作记录有 更新的选项， 这样 可刷新查看我们追剧是否有更新。
但是 目前的版本 不知道从什么时候起。突然没有了 这个功能。
当我们想 再看这个剧的时候需要重新搜索 才可以显示 更新到几集 
希望作者 修复一下  谢谢 支持大大

**Comment by cuiocean** [comment]
2.8.4版本,历史界面有"检查更新"选项啊.
![image](https://user-images.githubusercontent.com/5760235/120040815-7f6bb000-c007-11eb-94d1-0312c3544897.png)
