### ISSUE TITLE
2.8.4版本-检测到视频源未能正常加载, 即将重置源

### ISSUE THREAD

**Issue by Nicxhkhun** [cuiocean/ZY-Player#713]
### 版本、安装方式、系统

1. 你在使用什么版本的
      2.8.4
2. 你通过什么方式安装
      homebrew
3. 你所使用的操作系统
     macos11.2.3

### 描述问题：
![image](https://user-images.githubusercontent.com/26847642/120349170-75f88580-c330-11eb-8c5f-f4880c7448e1.png)

**Comment by BruceAn1978** [comment]
同问，下载后打开就是报错信息，没有任何视频。
