### ISSUE TITLE
请问这个打包问题怎么解决

### ISSUE THREAD

**Issue by HankMo** [cuiocean/ZY-Player#718]
### 版本、安装方式、系统

![image](https://user-images.githubusercontent.com/60347960/122662480-df4c1580-d1c5-11eb-8d80-650bf3e69713.png)

### 描述问题：
win10  vue/cli 4

打包错误

**Comment by Hunlongyu** [comment]
第一个是 组件缺失。 但是这个 HelloWorld.vue 组件在 ZY 中并没有用到， 你看看是不是在app.vue 里多写了。
第二个是 资源缺失。 软件 的logo 被你删除了吧， 查看 assets 是不是少了 logo.png 文件。补上就好了。
