### ISSUE TITLE
在macos10.14.6无法正常使用，源站无法显示

### ISSUE THREAD

**Issue by nabaonan** [cuiocean/ZY-Player#722]
**描述错误**
在macos10.14.6无法正常使用，源站无法显示

**重现**
源站显示为空，如果手动导入，软件左侧都会变成空白

**预期行为**
显示源站列表

**截图**
![image](https://user-images.githubusercontent.com/17247526/124953062-619e5b80-e047-11eb-9f02-b21770797bf9.png)
![image](https://user-images.githubusercontent.com/17247526/124953257-8e527300-e047-11eb-952f-117f9f851eab.png)
![image](https://user-images.githubusercontent.com/17247526/124953320-9f02e900-e047-11eb-8386-e1a42d7e6d79.png)

**环境：**
  -操作系统及版本：macos10.14.6
  -软件安装包及版本：2.8.4

**其他内容**

**Comment by Darling-Lee** [comment]
我同样一个系统版本。一直没问题，甚至现在的2.8.5版本。你可能需要完全卸载清除后重新安装一下

**Comment by nabaonan** [comment]
> 我同样一个系统版本。一直没问题，甚至现在的2.8.5版本。你可能需要完全卸载清除后重新安装一下

我一会儿试试1.8.5版本

**Comment by nabaonan** [comment]
> 载

安装了最新版，源站列表依然是没有的，我用的cleanMymac卸载的

**Comment by nabaonan** [comment]
重置软件设置之后，重置源之后就好了
