### ISSUE TITLE
我也用Flutter整了个手机版

### ISSUE THREAD

**Issue by d1y** [cuiocean/ZY-Player#747]
作者的tv版本好像没啥动静: https://github.com/cuiocean/ZY-Player-TV

所以我自己写了一个, 测试过 android / windows, 基本没啥问题(貌似:)

欢迎PR： https://github.com/waifu-project/movie

**Comment by b911ss** [comment]
支持大佬！再来个tv版本的吧！

**Comment by d1y** [comment]
> 支持大佬！再来个tv版本的吧！

tv指的是安卓电视盒子？

**Comment by b911ss** [comment]
> > 支持大佬！还有一个电视版本的吧！
> 
> tv指的是安卓电视盒子？

是的大佬！

**Comment by jinyulei** [comment]
已安装，喜欢。
